title: "Kasper Bågmark"
description: "Research in stochastic filtering, SDEs, neural fields, and UQ."
url: "https://bagmark.github.io"
baseurl: "" # for user site; for project site use "/reponame"
author:
  name: "Kasper Bågmark"
  avatar: "/assets/img/profile.png"   # <- path to your photo
  bio: "PhD student at Chalmers University of Technology & University of Gothenburg"
  email: "bagmark@chalmers.se"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:bagmark@chalmers.se"
    - label: "Chalmers profile"
      icon: "fas fa-building-columns"
      url: "https://www.chalmers.se/en/persons/bagmark/"                # paste your URL
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/kasper-bågmark-0098b9b1/"  # paste your URL
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=-oZDUnQAAAAJ"
    - label: "ORCID"
      icon: "fab fa-orcid"
      url: "https://orcid.org/0000-0002-9779-4761"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/bagmark"

defaults:
  - scope:
      path: ""      # all files
      type: pages   # only pages (not posts)
    values:
      layout: single
      author_profile: true

# Use a simple Jekyll theme via remote_theme (works on GitHub Pages)
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

# Minimal Mistakes settings
minimal_mistakes_skin: "air"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-include-cache

# Navigation
navigation:
  - title: "Home"
    url: /
  - title: "Publications"
    url: /publications/
  - title: "Contact"
    url: /#contact

# Collections (optional, not used here)
# collections:
#   posts:
#     output: true

# Permalinks
permalink: pretty

# Markdown
markdown: kramdown

# Build settings
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
